
stretchcurve_sizes:

    .db 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 
    .db 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4

stretchcurve_nametables:

    .db 0xf1 | (0 << 1)
    .db 0xf1 | (1 << 1)
    .db 0xf1 | (1 << 1)
    .db 0xf1 | (2 << 1)
    .db 0xf1 | (3 << 1)
    .db 0xf1 | (3 << 1)
    .db 0xf1 | (4 << 1)
    .db 0xf1 | (5 << 1)

    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)
    .db 0xf1 | (5 << 1)

